name: jarvis
description: Command-line interface (CLI) for generating a Flutter project
version: 0.0.5
homepage: https://github.com/holyboom1/jarvis.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  dio: ^5.5.0+1
  get_it: ^7.7.0
  logger: ^2.4.0
  args: ^2.5.0
  dcli: ^4.0.5
  mason_logger: ^0.2.16
  archive: ^3.6.1

  json_ast: ^1.0.6
  convert: ^3.1.1
  dart_style: ^2.3.6
  equatable: ^2.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

executables:
  jarvis:

